/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import entity.Assessment;
import controller.AssessmentController;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class AssessmentRecodsFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AssessmentRecodsFrame.class.getName());
    
    private List<Assessment> assessments;
    private AssessmentController controller;
    /**
     * Creates new form AssessmentRecodsFrame
     */
    public AssessmentRecodsFrame() {
        initComponents();
        this.assessments = new java.util.ArrayList<>();
        this.controller = new AssessmentController();
        populateTable();
        
    }
    private void populateTable() {
    // 1. Dapatkan model jadual JTable anda
    // Sila tukar 'jTable1' mengikut Nama Variable JTable sebenar anda di mod Design
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    // 2. Bersihkan jadual daripada sebarang data lama (supaya data tidak bertindih)
    model.setRowCount(0);
    
    // 3. Panggil Controller untuk ambil semua rekod dari database
    controller.AssessmentController controller = new controller.AssessmentController();
    java.util.ArrayList<entity.Assessment> list = controller.getAllAssessments();
    
    // 4. Masukkan data ke dalam jadual baris demi baris
    if (list != null) {
        for (entity.Assessment ass : list) {
            Object[] row = new Object[4];
            row[0] = ass.getAssessmentId();
            row[1] = ass.getTitle();
            row[2] = (ass.getInstructorId() != null) ? ass.getInstructorId() : "N/A";
            row[3] = (ass.getScore() >= 0) ? ass.getScore() + " / 100" : "PENDING";
            
            model.addRow(row);
        }
    } else {
            System.out.println("Log: Tiada data atau senarai assessment kosong dari database.");
        }
}
    
    private void populateTableData() {

    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        AssessmentController assessmentCtrl = new AssessmentController();
        java.util.List<entity.Assessment> allAssessments = assessmentCtrl.getAllAssessments();

        System.out.println("DEBUG: MySQL Database assessment size is currently: " + allAssessments.size());

        if (allAssessments == null || allAssessments.isEmpty()) {
            System.out.println("Status: No records found inside Text File Database.");
            return;
        }

        int index = 1;
        for (entity.Assessment record : allAssessments) {
            String fileName = "Submission_" + record.getAssessmentId() + ".pdf"; 
            String currentScore = "Pending Grading";
            
            // KOD RASMI: Ekstrak markah daripada description jika sudah digred
            String desc = record.getDescription();
            if (desc != null && desc.contains("| Marks:")) {
                try {
                    // Mengambil data selepas perkataan "| Marks: " sehingga "/"
                    int start = desc.indexOf("| Marks:") + 9;
                    int end = desc.indexOf("/100");
                    if (end > start) {
                        currentScore = desc.substring(start, end).trim() + " / 100";
                    }
                } catch (Exception e) {
                    currentScore = "Graded";
                }
            }

            Object[] rowData = {
                record.getAssessmentId(), // Menggunakan ID sebenar sebagai rujukan baris
                record.getTitle(),
                fileName,
                currentScore
            };
            model.addRow(rowData);
            index++;
        }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        lblStatusMessage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("MASTER ASSESSMENT RECORDS (DATABASE ARRAY)");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Record ID", "Assessment Title", "Uploaded Student File", "Final Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        btnRefresh.setText("REFRESH DATA");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnViewDetails.setText("OPEN SELECTED RESULT");
        btnViewDetails.addActionListener(this::btnViewDetailsActionPerformed);

        lblStatusMessage.setText("Status: Ready");

        jButton1.setText("CREATE NEW ASSESSMENT");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("EDIT RECORD");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("DELETE RECORD");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewDetails)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButton3)))))
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(lblStatusMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatusMessage)
                    .addComponent(btnRefresh))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an assessment from the table first!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. Ambil ID dari Kolum 0 (Kolum pertama jadual iaitu Record ID)
    String idDariJadual = jTable1.getValueAt(selectedRow, 0).toString();
    
    // 3. Buka skrin gred SAMBIL hantar ID tersebut masuk ke dalam constructor baharu kita!
    GradeAssessmentFrame gradeScreen = new GradeAssessmentFrame(idDariJadual);
    gradeScreen.setVisible(true);
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateTable();
        populateTableData();
        javax.swing.JOptionPane.showMessageDialog(this, "Data refreshed successfully!");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CreateAssessmentFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "PLEASE SELECT ANY RECORDS IN THE TABLE TO BE EDITED!");
            return;
        }
        
        // KOD RASMI: Ambil ID Assessment dari Kolum 0 (Record ID) baris yang dipilih
        String selectedId = jTable1.getValueAt(selectedRow, 0).toString();
        
        // Buka GradeAssessmentFrame dengan menghantar ID tugasan terpilih
        new GradeAssessmentFrame(selectedId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "PLEASE SELECT ANY RECORDS IN THE TABLE TO BE DELETED!");
        return;
    }
    
    // 1. Ambil ID Assessment dari baris yang dipilih (Kolum 0)
    String selectedId = jTable1.getValueAt(selectedRow, 0).toString();
    
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Do you want to delete assessment " + selectedId + " from Database?", "DELETION CONFIRM", 
            javax.swing.JOptionPane.YES_NO_OPTION);
            
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // Konfigurasi sambungan database port 3307 anda
        String url = "jdbc:mysql://localhost:3307/primeedu_db";
        String user = "root";
        String password = "";
        
        // Arahan SQL untuk padam rekod berdasarkan ID
        String sql = "DELETE FROM assessments WHERE assessment_id = ?";
        
        try (java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, password);
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, selectedId);
            int rowsDeleted = pstmt.executeUpdate();
            
            if (rowsDeleted > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "RECORD DELETION SUCCESSFUL FROM DATABASE!");
                populateTableData(); // Refresh jadual terus secara automatik
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Record not found in database.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AssessmentRecodsFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblStatusMessage;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
