/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import controller.QuizController;
import entity.Question;
import javax.swing.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class CreateQuestionFrame extends javax.swing.JFrame {
    
    private String quizTitle;
    private java.util.Date quizDueDate;
    private int quizTimeLimit;
    private int totalQuestionsAdded = 0;
    private ArrayList<Question> quizQuestions = new ArrayList<>();
    
    
    public CreateQuestionFrame(String title, java.util.Date dueDate, int timeLimit) {
        initComponents();
        
        this.quizTitle = title;
        this.quizDueDate = dueDate;
        this.quizTimeLimit = timeLimit;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestionPrompt = new javax.swing.JTextArea();
        txtOptA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOptB = new javax.swing.JTextField();
        txtOptC = new javax.swing.JTextField();
        txtOptD = new javax.swing.JTextField();
        cmbCorrectAnswer = new javax.swing.JComboBox<>();
        btnAddQuestion = new javax.swing.JButton();
        btnPublishQuiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ENTER QUESTION:");

        txtQuestionPrompt.setColumns(20);
        txtQuestionPrompt.setRows(5);
        jScrollPane1.setViewportView(txtQuestionPrompt);

        txtOptA.setText("Option A");

        jLabel2.setText("ANSWER: ");

        txtOptB.setText("Option B");
        txtOptB.addActionListener(this::txtOptBActionPerformed);

        txtOptC.setText("Option C");

        txtOptD.setText("Option D");

        cmbCorrectAnswer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", " " }));
        cmbCorrectAnswer.addActionListener(this::cmbCorrectAnswerActionPerformed);

        btnAddQuestion.setText("ADD MORE");
        btnAddQuestion.addActionListener(this::btnAddQuestionActionPerformed);

        btnPublishQuiz.setText("PUBLISH");
        btnPublishQuiz.addActionListener(this::btnPublishQuizActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOptD, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(txtOptC)
                            .addComponent(txtOptB)
                            .addComponent(txtOptA))
                        .addGap(18, 18, 18)
                        .addComponent(cmbCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnPublishQuiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddQuestion)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOptA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOptB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOptC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOptD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddQuestion)
                    .addComponent(btnPublishQuiz))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOptBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOptBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOptBActionPerformed

    private void cmbCorrectAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCorrectAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCorrectAnswerActionPerformed

    private void btnPublishQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublishQuizActionPerformed
        String questionPrompt = txtQuestionPrompt.getText().trim();
        String optA = txtOptA.getText().trim();
        String optB = txtOptB.getText().trim();
        String optC = txtOptC.getText().trim();
        String optD = txtOptD.getText().trim();
        String correctAns = (String) cmbCorrectAnswer.getSelectedItem();

        // Jika kotak soalan tidak kosong, maksudnya user sedang taip soalan terakhir tetapi belum tekan ADD MORE
        if (!questionPrompt.isEmpty()) {
            if (optA.isEmpty() || optB.isEmpty() || optC.isEmpty() || optD.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "You are currently typing a question. Please complete all choices (A-D) before publishing!", 
                    "Warning", JOptionPane.WARNING_MESSAGE);
                return; 
            }
            
            // Masukkan soalan terakhir ini ke dalam list secara automatik
            Question q = new Question();
            q.setQuestionPrompt(questionPrompt);
            q.setOptionA(optA);
            q.setOptionB(optB);
            q.setOptionC(optC);
            q.setOptionD(optD);
            q.setCorrectAnswer(correctAns); 
            
            quizQuestions.add(q);
            System.out.println("Final Question #" + quizQuestions.size() + " automatically added before publishing.");
        }

        // Validasi: Sekat jika list memang kosong dari awal
        if (quizQuestions.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Error: Cannot publish an empty quiz! Please add at least 1 question.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.io.File quizFile = new java.io.File("quiz_database.txt");
        
        try (java.io.FileWriter fw = new java.io.FileWriter(quizFile, true); 
             java.io.BufferedWriter bw = new java.io.BufferedWriter(fw)) {
            
            bw.write("=== QUIZ_START ===" + "," + this.quizTitle + "," + this.quizTimeLimit);
            bw.newLine();
            
            for (Question q : quizQuestions) {
                String line = q.getQuestionPrompt() + "," +
                              q.getOptionA() + "," +
                              q.getOptionB() + "," +
                              q.getOptionC() + "," +
                              q.getOptionD() + "," +
                              q.getCorrectAnswer();
                bw.write(line);
                bw.newLine(); 
            }
            
            bw.write("=== QUIZ_END ===");
            bw.newLine();
            bw.flush(); 

            JOptionPane.showMessageDialog(this, 
                "Quiz permanently saved to text file: " + quizFile.getName() + "!\nTotal questions: " + quizQuestions.size(), 
                "File I/O Success", 
                JOptionPane.INFORMATION_MESSAGE);

            AnswerQuizFrame studentView = new AnswerQuizFrame(this.quizTitle, this.quizDueDate, this.quizTimeLimit, quizQuestions);
            studentView.setVisible(true);
            this.dispose();

        } catch (java.io.IOException ex) {
            JOptionPane.showMessageDialog(this, 
                "System File Error: Failed to write to text file.\n" + ex.getMessage(), 
                "I/O Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPublishQuizActionPerformed

    private void btnAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQuestionActionPerformed

        String questionPrompt = txtQuestionPrompt.getText().trim();
        String optA = txtOptA.getText().trim();
        String optB = txtOptB.getText().trim();
        String optC = txtOptC.getText().trim();
        String optD = txtOptD.getText().trim();
        String correctAns = (String) cmbCorrectAnswer.getSelectedItem();

        if (questionPrompt.isEmpty() || optA.isEmpty() || optB.isEmpty() || optC.isEmpty() || optD.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please complete the question prompt and all choices (A-D) first!", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return; 
        }

        Question q = new Question();
        q.setQuestionPrompt(questionPrompt);
        q.setOptionA(optA);
        q.setOptionB(optB);
        q.setOptionC(optC);
        q.setOptionD(optD);
        
        q.setCorrectAnswer(correctAns); 

        quizQuestions.add(q);

        System.out.println("Question #" + quizQuestions.size() + " successfully added to memory.");
        System.out.println("Answer Key set to Option: " + correctAns);
        
        JOptionPane.showMessageDialog(this, 
            "Question #" + quizQuestions.size() + " added to the quiz queue successfully!",
            "Success",
            JOptionPane.INFORMATION_MESSAGE);

        txtQuestionPrompt.setText("");
        txtOptA.setText("Option A");
        txtOptB.setText("Option B");
        txtOptC.setText("Option C");
        txtOptD.setText("Option D");
        cmbCorrectAnswer.setSelectedIndex(0);
    
    }//GEN-LAST:event_btnAddQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CreateQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreateQuestionFrame("Test Quiz", null, 30).setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddQuestion;
    private javax.swing.JButton btnPublishQuiz;
    private javax.swing.JComboBox<String> cmbCorrectAnswer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtOptA;
    private javax.swing.JTextField txtOptB;
    private javax.swing.JTextField txtOptC;
    private javax.swing.JTextField txtOptD;
    private javax.swing.JTextArea txtQuestionPrompt;
    // End of variables declaration//GEN-END:variables

}
