/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import controller.AssessmentController;
import entity.Assessment;
import java.io.File;
import javax.swing.JOptionPane;

public class GradeAssessmentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GradeAssessmentFrame.class.getName());
    private String assessmentId ;
    private java.io.File studentFile;
    private final int MAX_SCORE = 100;

    /**
     * Creates new form GradeAssessmentFrame
     */
    
    public GradeAssessmentFrame(String selectedAssessmentId) { 
        initComponents();
        this.assessmentId = selectedAssessmentId;
        loadAssessmentData();
    }
    
    public GradeAssessmentFrame() {
        initComponents();
        loadAssessmentData();
    }
    
    private void loadAssessmentData() {
        // Jika tiada ID dihantar (panggilan kosong), set nilai lalai ringkas
        if (this.assessmentId == null || this.assessmentId.isEmpty()) {
            lblAssignmentName.setText("Assessment: NO ASSESSMENT SELECTED");
            lblFileNameDisplay.setText("No file received.");
            txtFilePathDisplay.setText("");
            return;
        }
        
        AssessmentController controller = new AssessmentController();
        java.util.List<Assessment> allAssessments = controller.getAllAssessments();
        Assessment activeRecord = null;
        
        if (allAssessments != null) {
            for (Assessment ass : allAssessments) {
                if (ass.getAssessmentId() != null && ass.getAssessmentId().equalsIgnoreCase(this.assessmentId)) {
                    activeRecord = ass;
                    break;
                }
            }
        }
        
        if (activeRecord != null) {
        lblAssignmentName.setText("Assessment: " + activeRecord.getTitle().toUpperCase());
    
        String desc = activeRecord.getDescription(); 
        lblFileNameDisplay.setText("Record Data: " + desc);
   
        String studentFileName = "Assessments.txt"; // Fallback default
        if (desc != null && desc.contains("Student Submission:")) {
        // Ekstrak nama fail selepas perkataan "Student Submission: "
        studentFileName = desc.substring(desc.indexOf("Student Submission:") + 19).trim();
    }
    
    txtFilePathDisplay.setText(studentFileName);
    this.studentFile = new java.io.File(studentFileName);
        } else {
            lblFileNameDisplay.setText("No data found.");
            txtFilePathDisplay.setText("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblAssignmentName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFileNameDisplay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFilePathDisplay = new javax.swing.JTextField();
        btnOpenFile = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSaveGrade = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCommentInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHeader.setText("INSTRUCTOR GRADING TERMINAL");

        lblAssignmentName.setText("Assessment: [Name]");

        jLabel3.setText("Submitted File:");

        lblFileNameDisplay.setText("filename.pdf");

        jLabel5.setText("System File Path:");

        btnOpenFile.setText("Open / Download File");
        btnOpenFile.addActionListener(this::btnOpenFileActionPerformed);

        jLabel6.setText("Enter Student Score:");

        jLabel7.setText("/ 100");

        btnSaveGrade.setText("SAVE MARKS");
        btnSaveGrade.addActionListener(this::btnSaveGradeActionPerformed);

        btnBack.setText("Back to Dashboard");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jTextField2.setColumns(5);

        jLabel1.setText("Comment:");

        txtCommentInput.addActionListener(this::txtCommentInputActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnBack)
                        .addGap(57, 57, 57)
                        .addComponent(btnSaveGrade))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAssignmentName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCommentInput, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(btnOpenFile)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFileNameDisplay)
                                    .addComponent(txtFilePathDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addComponent(lblAssignmentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblFileNameDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilePathDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpenFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCommentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSaveGrade))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        if (studentFile != null && studentFile.exists()) {
            try {
                java.awt.Desktop.getDesktop().open(studentFile);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: Unable to open the file.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No physical file available to open.", "File Missing", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void btnSaveGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveGradeActionPerformed
    String id = this.assessmentId; 
        
        // Validasi 1: Pastikan ID tidak kosong/null
        if (id == null || id.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "System Error: Assessment ID is missing!\nPlease open this frame from the Records Table.", 
                "System Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validasi 2: Ambil input markah dari jTextField2 dan pastikan tidak kosong
        String scoreText = jTextField2.getText().trim();
        if (scoreText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a student score first!", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Tukar String markah kepada Integer dengan selamat
        int gred = 0;
        try {
            gred = Integer.parseInt(scoreText);
            
            // Validasi julat markah (0 - 100)
            if (gred < 0 || gred > MAX_SCORE) {
                javax.swing.JOptionPane.showMessageDialog(this, "Score must be between 0 and 100!", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Score must be a valid number!", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 3. Ambil nilai komen daripada 'txtCommentInput' (Sebab nama variable anda txtCommentInput)
        String komen = txtCommentInput.getText().trim(); 
        
        // 4. Panggil Controller untuk hantar data ke database MySQL
        controller.AssessmentController assessmentController = new controller.AssessmentController();
        boolean success = assessmentController.saveAssessmentGrade(id, gred, komen);
        
        // 5. Papar status kejayaan/kegagalan kepada guru
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Grade (" + gred + "/100) and feedback saved successfully to database!", 
                "Success", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
            // Buka semula jadual rekod yang telah dikemas kini dan tutup skrin gred ini
            new AssessmentRecodsFrame().setVisible(true);
            this.dispose(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Database Error: Failed to update records.\n(Tip: Ensure Assessment ID '" + id + "' matches 'assessment_id' column in phpMyAdmin)", 
                "System Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveGradeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new AssessmentRecodsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCommentInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommentInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(GradeAssessmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GradeAssessmentFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnSaveGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAssignmentName;
    private javax.swing.JLabel lblFileNameDisplay;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextField txtCommentInput;
    private javax.swing.JTextField txtFilePathDisplay;
    // End of variables declaration//GEN-END:variables
}
