/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
public class ProvideFeedbackFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProvideFeedbackFrame.class.getName());

    private final int MAX_CHAR_LIMIT = 250; 
    private String currentAssessmentTitle;
    
    public ProvideFeedbackFrame(String assessmentTitle) {
        initComponents();
        this.currentAssessmentTitle = assessmentTitle;
        lblAssessmentName.setText("Feedback For: " + assessmentTitle.toUpperCase());
        setupCharacterCounter();
    }

    public ProvideFeedbackFrame() {
        initComponents();
        setupCharacterCounter();
    }
    
    private void setupCharacterCounter() {
        txtFeedbackArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { updateCount(); }
            @Override
            public void removeUpdate(DocumentEvent e) { updateCount(); }
            @Override
            public void changedUpdate(DocumentEvent e) { updateCount(); }
            
            private void updateCount() {
                int length = txtFeedbackArea.getText().length();
                lblCharCount.setText("Characters: " + length + " / " + MAX_CHAR_LIMIT);
                
                // Tukar warna teks jadi merah jika lebih had limit
                if (length > MAX_CHAR_LIMIT) {
                    lblCharCount.setForeground(java.awt.Color.RED);
                } else {
                    lblCharCount.setForeground(new java.awt.Color(102, 102, 102));
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAssessmentName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFeedbackArea = new javax.swing.JTextArea();
        lblCharCount = new javax.swing.JLabel();
        btnSubmitFeedback = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitle.setText("PROVIDE LEARNING FEEDBACK");

        lblAssessmentName.setText("Feedback For: [ASSESSMENT NAME]");

        jLabel3.setText("Write your wanted comments / feedback about the learning process:");

        txtFeedbackArea.setColumns(20);
        txtFeedbackArea.setLineWrap(true);
        txtFeedbackArea.setRows(5);
        txtFeedbackArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtFeedbackArea);

        lblCharCount.setText("Characters: 0 / 250");

        btnSubmitFeedback.setText("SUBMIT FEEDBACK");
        btnSubmitFeedback.addActionListener(this::btnSubmitFeedbackActionPerformed);

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblAssessmentName)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCharCount)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(64, 64, 64)
                .addComponent(btnSubmitFeedback)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblAssessmentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCharCount)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitFeedback)
                    .addComponent(btnCancel))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitFeedbackActionPerformed
        String feedbackText = txtFeedbackArea.getText().trim();
        
        if (feedbackText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Validation Error: Feedback comment cannot be empty!\nPlease write a valid comment before submitting.", 
                    "Empty Feedback", 
                    JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        if (feedbackText.length() > MAX_CHAR_LIMIT) {
            JOptionPane.showMessageDialog(this, 
                    "Validation Error: Your feedback exceeds the maximum allowed limit of " + MAX_CHAR_LIMIT + " characters!", 
                    "Character Limit Exceeded", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.io.File feedbackFile = new java.io.File("learning_feedback.txt");
       
        try (java.io.FileWriter fw = new java.io.FileWriter(feedbackFile, true);
             java.io.BufferedWriter bw = new java.io.BufferedWriter(fw)) {
            
            String timestamp = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());
           
            String cleanFeedback = feedbackText.replace("\n", " ").replace(",", ";"); 
            
            String recordLine = timestamp + " | " + this.currentAssessmentTitle + " | " + cleanFeedback;
            
            bw.write(recordLine);
            bw.newLine(); 
            bw.flush();
            
            JOptionPane.showMessageDialog(this, 
                    "Feedback stored and submitted successfully to '" + feedbackFile.getName() + "'!\nIt is now visible to students, parents, and teachers.", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
           
            this.dispose();
            
        } catch (java.io.IOException ex) {
            JOptionPane.showMessageDialog(this, 
                    "System File Error: Failed to save feedback to text file.\n" + ex.getMessage(), 
                    "I/O Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitFeedbackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ProvideFeedbackFrame("Object-Oriented Design & Implementation (OODI)").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmitFeedback;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssessmentName;
    private javax.swing.JLabel lblCharCount;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtFeedbackArea;
    // End of variables declaration//GEN-END:variables
}
