/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import controller.AssessmentController;
import entity.Assessment;
import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class SubmitAssessmentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubmitAssessmentFrame.class.getName());

    private String assessmentId;
    private Date assessmentDueDate;
    private File studentAttachedFile = null;
    
    public SubmitAssessmentFrame(String selectedId) {
        initComponents();
        
        this.assessmentId = selectedId;
        loadActiveAssessment();
    }
    
    public SubmitAssessmentFrame() {
        initComponents();
        loadActiveAssessment();
    }
    
    private void loadActiveAssessment() {
        if (this.assessmentId == null || String.valueOf(this.assessmentId).isEmpty()) {
            lblAssessmentTitle.setText("NO ASSESSMENT SELECTED");
            return;
        }

        AssessmentController controller = new AssessmentController();
        java.util.List<Assessment> allAssessments = controller.getAllAssessments();
        Assessment activeRecord = null;

        if (allAssessments != null) {
            for (Assessment ass : allAssessments) {
                if (ass.getAssessmentId() != null && ass.getAssessmentId().equalsIgnoreCase(this.assessmentId)) {
                    activeRecord = ass;
                    break;
                }
            }
        }

        if (activeRecord != null) {
            lblAssessmentTitle.setText(activeRecord.getTitle().toUpperCase());
            jTextField1.setText(activeRecord.getAssessmentId());
            jTextField1.setEditable(false);
            
            this.assessmentDueDate = activeRecord.getDueDate(); 
            
            if (this.assessmentDueDate != null) {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
                lblDueDateDisplay.setText("Due Date: " + sdf.format(this.assessmentDueDate));
            }
        } else {
            lblAssessmentTitle.setText("ASSESSMENT: " + this.assessmentId.toUpperCase());
            jTextField1.setText(this.assessmentId);
            jTextField1.setEditable(false);
        }
        
        checkDueDateRestriction();
    }
    
    private void checkDueDateRestriction() {
        Date today = new Date(); 
        
        if (assessmentDueDate != null && today.after(assessmentDueDate)) {
            JOptionPane.showMessageDialog(this, 
                "The due date for this assessment has passed!\nYou can no longer upload or submit any files.", 
                "Submission Closed", 
                JOptionPane.ERROR_MESSAGE);
            
            btnBrowse.setEnabled(false);
            btnSubmitAssessment.setEnabled(false);
            lblFilePath.setText("SUBMISSION CLOSED (LATE)");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAssessmentTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDueDateDisplay = new javax.swing.JLabel();
        lblFilePath = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnSubmitAssessment = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAssessmentTitle.setText("ASSESSMENT TITLE:");

        lblDueDateDisplay.setText("Due Date: YYYY-MM-DD");

        lblFilePath.setText("Select your submission file (PDF, Docx, Zip):");

        btnBrowse.setText("Browse File");
        btnBrowse.addActionListener(this::btnBrowseActionPerformed);

        btnSubmitAssessment.setText("SUBMIT");
        btnSubmitAssessment.addActionListener(this::btnSubmitAssessmentActionPerformed);

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("ASSESSMENT SUBMISSION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmitAssessment, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFilePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowse)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDueDateDisplay)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAssessmentTitle)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssessmentTitle)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDueDateDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilePath)
                    .addComponent(btnBrowse))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitAssessment)
                    .addComponent(btnCancel))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int response = fileChooser.showOpenDialog(this);
        
        if (response == JFileChooser.APPROVE_OPTION) {
            studentAttachedFile = fileChooser.getSelectedFile();
            lblFilePath.setText(studentAttachedFile.getName());
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnSubmitAssessmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAssessmentActionPerformed
        if (studentAttachedFile == null || !studentAttachedFile.exists()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please browse and select a valid file first!");
            return;
        }

        AssessmentController controller = new AssessmentController();
        
        String submissionInfo = "Student Submission: " + studentAttachedFile.getName();
        
        boolean success = controller.updateAssessmentDescription(this.assessmentId, submissionInfo);
        
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "File " + studentAttachedFile.getName() + " successfully uploaded and submitted!",
                "Submission Success",
                JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "System Error: Failed to record your file submission.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitAssessmentActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(SubmitAssessmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SubmitAssessmentFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmitAssessment;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAssessmentTitle;
    private javax.swing.JLabel lblDueDateDisplay;
    private javax.swing.JLabel lblFilePath;
    // End of variables declaration//GEN-END:variables
}
