/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import controller.AssessmentController;
import entity.Assessment;
import javax.swing.JOptionPane;

public class ViewMarksFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewMarksFrame.class.getName());

    private String assessmentId = "";
    private String assessmentTitle;
    private int studentScore;
    private String teacherComment;
    
    public ViewMarksFrame(String selectedAssessmentId) {
        initComponents();
        
        this.assessmentId = selectedAssessmentId;
        loadDataFromController();
    }
    
    public ViewMarksFrame() {
        initComponents();
        
        this.assessmentId = "A001"; // Default ID jika dibuka terus
        loadDataFromController();
    }
    
    private void loadDataFromController() {
        AssessmentController controller = new AssessmentController();
        Assessment record = controller.getAssessmentById(this.assessmentId);
        
        if (record != null) {
            this.assessmentTitle = record.getTitle();
            
            // TERUS AMBIL DARI ENTITI (DATABASE) TANPA PERLU POTONG TEKS!
            this.studentScore = record.getScore(); 
            this.teacherComment = record.getTeacherComment();
            
            // Jika kolum 'score' di database adalah NULL atau belum digred, pastikan ada nilai default
            if (this.teacherComment == null) {
                this.teacherComment = "No feedback provided yet.";
            }
            
            // Di sini kita boleh semak status: jika guru belum masukkan markah (atau kekal null/-1)
            boolean isGraded = (this.studentScore >= 0); 
            
            displayMarkDetails(this.assessmentTitle, this.studentScore, this.teacherComment, isGraded);
        } else {
            displayMarkDetails("No Assessment Loaded", 0, "", false);
        }
    }
    
    private void displayMarkDetails(String title, int score, String comment, boolean isGraded) {
        lblAssessmentTitleDisplay.setText(title);
        lblScoreDisplay.setText(score + " / 100");
        txtCommentDisplay.setText(comment);
    
        // Memastikan penentuan status adalah tepat dan kalis ralat
        if (isGraded) {
            lblStatus.setText("STATUS: GRADED");
            lblStatus.setForeground(new java.awt.Color(0, 153, 51)); // (Opsional) Warna hijau untuk GRADED
        } else {
            lblStatus.setText("STATUS: PENDING");
            lblStatus.setForeground(new java.awt.Color(255, 153, 0)); // (Opsional) Warna oren untuk PENDING
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAssessmentTitleDisplay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblScoreDisplay = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCommentDisplay = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHeader.setText("ASSESSMENT RESULT AND COMMENT");

        jLabel2.setText("Assessment Name:");

        lblAssessmentTitleDisplay.setText("[ASSESSMENT TITLE]");

        jLabel4.setText("Final Score Obtained:");

        lblScoreDisplay.setText("0 / 100");

        jLabel6.setText("Teacher's Feedback & Comments:");

        txtCommentDisplay.setEditable(false);
        txtCommentDisplay.setColumns(20);
        txtCommentDisplay.setRows(4);
        jScrollPane1.setViewportView(txtCommentDisplay);

        btnClose.setText("Close & Exit View");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        lblStatus.setText("STATUS: PENDING");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(btnClose))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAssessmentTitleDisplay)
                                    .addComponent(lblScoreDisplay))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAssessmentTitleDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblScoreDisplay))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(ViewMarksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new ViewMarksFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssessmentTitleDisplay;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblScoreDisplay;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextArea txtCommentDisplay;
    // End of variables declaration//GEN-END:variables
}
