/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Module2.boundary;

/**
 *
 * @author Arun
 */
public class DashboardUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardUI.class.getName());

    /**
     * Creates new form DashboardUI
     */
    public DashboardUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateSubject = new javax.swing.JButton();
        btnUploadMaterial = new javax.swing.JButton();
        btnTimetable = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateSubject.setText("Create Subjects");
        btnCreateSubject.addActionListener(this::btnCreateSubjectActionPerformed);
        getContentPane().add(btnCreateSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 172, -1, -1));

        btnUploadMaterial.setText("Upload Material");
        btnUploadMaterial.addActionListener(this::btnUploadMaterialActionPerformed);
        getContentPane().add(btnUploadMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 172, -1, -1));

        btnTimetable.setText("Timetable");
        btnTimetable.addActionListener(this::btnTimetableActionPerformed);
        getContentPane().add(btnTimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 172, -1, -1));

        jButton1.setText("View Records");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 172, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PrimeEdu Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 31, 261, 69));

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(612, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnLogout)
                .addContainerGap(442, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSubjectActionPerformed
        CreateSubjectUI createScreen = new CreateSubjectUI();
        
        // 2. Make the new window visible to the user
        createScreen.setVisible(true);
        
        // 3. (Optional) Hide the main dashboard so the screen doesn't get cluttered
        // If you want the dashboard to stay open in the background, just leave this commented out!
        this.dispose(); 
    

    }//GEN-LAST:event_btnCreateSubjectActionPerformed

    private void btnUploadMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadMaterialActionPerformed
        // 1. Create the new Upload screen
    UploadMaterialUI uploadScreen = new UploadMaterialUI();
    
    // 2. Show it to the user
    uploadScreen.setVisible(true);
    
    // 3. Close the dashboard
    this.dispose();
    }//GEN-LAST:event_btnUploadMaterialActionPerformed

    private void btnTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimetableActionPerformed
        // 1. Create the new Timetable screen
    TimetableUI timetableScreen = new TimetableUI();
    
    // 2. Show it to the user
    timetableScreen.setVisible(true);
    
    // 3. Close the dashboard
    this.dispose();
    }//GEN-LAST:event_btnTimetableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ViewRecordsUI viewScreen = new ViewRecordsUI();
    viewScreen.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // 1. Ask for confirmation before logging out
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm Logout", javax.swing.JOptionPane.YES_NO_OPTION);
        
        // 2. If they click "Yes"
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            
            // Re-open the Login screen
           LoginUI loginScreen = new LoginUI();
           loginScreen.setVisible(true);
            
            // Close the current Dashboard screen
            this.dispose();
        }
        // If they click "No", the pop-up just closes and nothing happens!
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateSubject;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTimetable;
    private javax.swing.JButton btnUploadMaterial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}