/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Module2.boundary;

import Module2.controller.SubjectController;
import Module2.entity.Subject;

/**
 *
 * @author Arun
 */
public class TimetableUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TimetableUI.class.getName());

    /**
     * Creates new form TimetableUI
     */
    public TimetableUI() {
    initComponents();
    updateTimetable("Std 4"); // <--- Add this!
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTimetable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cmbFilter = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTimetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ));
        jScrollPane1.setViewportView(tblTimetable);

        jButton1.setText("< Back to Dashboard");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Std 4", "Std 5", "Std 6" }));
        cmbFilter.addActionListener(this::cmbFilterActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Open the main Dashboard again
    DashboardUI dashboard = new DashboardUI();
    dashboard.setVisible(true);
    
    // 2. Close this current timetable screen
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
       updateTimetable(cmbFilter.getSelectedItem().toString());
    }//GEN-LAST:event_cmbFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TimetableUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTimetable;
    // End of variables declaration//GEN-END:variables

    private void updateTimetable(String standardFilter) {

    SubjectController controller = new SubjectController();

    java.util.ArrayList<Subject> allSubjects =
            controller.getSubjectList();

    java.util.ArrayList<Subject> filteredSubjects =
            new java.util.ArrayList<>();

    for (Subject s : allSubjects) {
        if (s.getStandard().equals(standardFilter)) {
            filteredSubjects.add(s);
        }
    }

    String[] columns = {
        "Time",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday"
    };

    Object[][] data = new Object[4][6];

    data[0][0] = "7:00 PM - 8:00 PM";
    data[1][0] = "8:00 PM - 9:00 PM";
    data[2][0] = "9:00 PM - 9:15 PM";
    data[3][0] = "9:15 PM - 10:15 PM";

    for (int i = 1; i <= 5; i++) {
        data[2][i] = "REST";
    }

    int subjectIndex = 0;

    for (int row = 0; row < 4; row++) {

        if (row == 2) {
            continue;
        }

        for (int col = 1; col <= 5; col++) {

            if (!filteredSubjects.isEmpty()) {

                Subject s =
                        filteredSubjects.get(subjectIndex % filteredSubjects.size());

                data[row][col] = s.getName();
                subjectIndex++;

            } else {

                data[row][col] = "Free Period";
            }
        }
    }

    javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel(data, columns);

    tblTimetable.setModel(model);
}
}