/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Module2.boundary;

import Module2.controller.MaterialController;
import Module2.controller.SubjectController;
import Module2.entity.Subject;

/**
 *
 * @author Arun
 */
public class UploadMaterialUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UploadMaterialUI.class.getName());

    /**
     * Creates new form UploadMaterialUI
     */
    public UploadMaterialUI() {
        initComponents();
        loadSubjectsIntoDropdown();
    }
    
    private void loadSubjectsIntoDropdown() {

    SubjectController subjectControl = new SubjectController();

    java.util.ArrayList<Subject> subjects =
            subjectControl.getSubjectList();

    cmbSubjects.removeAllItems();

    for (Subject s : subjects) {

        cmbSubjects.addItem(
                s.getCode() + " - "
                + s.getName() + " - "
                + s.getStandard()
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmbSubjects = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtInstructor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Subject Code");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel2.setText("File/Link:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        txtFilePath.addActionListener(this::txtFilePathActionPerformed);
        getContentPane().add(txtFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 170, -1));

        btnBrowse.setText("Browse...");
        btnBrowse.addActionListener(this::btnBrowseActionPerformed);
        getContentPane().add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, 22));

        btnUpload.setText("Upload Material");
        btnUpload.addActionListener(this::btnUploadActionPerformed);
        getContentPane().add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jButton1.setText("< Back to Dashboard");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 388, -1, -1));

        cmbSubjects.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSubjects.addActionListener(this::cmbSubjectsActionPerformed);
        getContentPane().add(cmbSubjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

        jLabel3.setText("Instructor Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        txtInstructor.addActionListener(this::txtInstructorActionPerformed);
        getContentPane().add(txtInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 160, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arun\\Downloads\\ChatGPT Image Jun 9, 2026, 01_22_41 .png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilePathActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
                                                
        // 1. Create the File Explorer window
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        
        // 2. Show the window and wait for the user to hit "Open" or "Cancel"
        int response = fileChooser.showOpenDialog(this);
        
        // 3. Check if they actually picked a file (meaning they didn't hit cancel)
        if (response == javax.swing.JFileChooser.APPROVE_OPTION) {
            
            // Grab the exact file they clicked on
            java.io.File selectedFile = fileChooser.getSelectedFile();
            
            // Take the full path of that file and paste it into your text box!
            txtFilePath.setText(selectedFile.getAbsolutePath());
        }
    
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
  // 1. Grab the exact text from the dropdown
        String selectedItem = cmbSubjects.getSelectedItem().toString();
        
        // 2. Split the text into pieces
        String[] parts = selectedItem.split(" - ");

// ... (Keep your existing dropdown splitting code at the top) ...
        String subjectCode = parts[0]; 
        String standard = parts[2];    
        
        // Grab the new instructor name and the file path
        String instructor = txtInstructor.getText(); 
        String filePath = txtFilePath.getText(); 
        
        if (filePath.isEmpty() || instructor.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an instructor name and browse for a file!");
            return;
        }

        // Send ALL FOUR pieces to the controller!
        MaterialController matControl = new MaterialController();
        matControl.addMaterial(subjectCode, standard, instructor, filePath);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Material successfully linked to " + subjectCode + "!");
        
    
    }//GEN-LAST:event_btnUploadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DashboardUI dashboard = new DashboardUI();
    dashboard.setVisible(true);
    // 2. Destroy this current screen so it doesn't pile up!
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubjectsActionPerformed
        
        

        
    }//GEN-LAST:event_cmbSubjectsActionPerformed

    private void txtInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UploadMaterialUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cmbSubjects;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtInstructor;
    // End of variables declaration//GEN-END:variables
}