/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Module2.boundary;

import Module2.controller.MaterialController;
import Module2.controller.SubjectController;
import Module2.entity.Subject;

/**
 *
 * @author Arun
 */
public class ViewRecordsUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewRecordsUI.class.getName());

    /**
     * Creates new form ViewRecordsUI
     */
   public ViewRecordsUI() {
        initComponents();
        refreshTable("All Standards", ""); // <--- Update this line!
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubjects = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cmbFilter = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        btnOpenMaterial = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSubjects);

        jButton1.setText("< Back to Dashboard");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnDelete.setText("Delete Selected");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Standards", "Std 4", "Std 5", "Std 6" }));
        cmbFilter.addActionListener(this::cmbFilterActionPerformed);

        btnEdit.setText("Edit Selected");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnOpenMaterial.setText("Manage Materials");
        btnOpenMaterial.addActionListener(this::btnOpenMaterialActionPerformed);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 104, Short.MAX_VALUE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOpenMaterial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnOpenMaterial)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DashboardUI dashboard = new DashboardUI();
    dashboard.setVisible(true);
    // 2. Destroy this current screen so it doesn't pile up!
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // 1. Figure out which row the user clicked on in the table
        int selectedRow = tblSubjects.getSelectedRow();
        
        // If it equals -1, it means they didn't click on anything!
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please click on a subject in the table to delete it.");
            return;
        }
        
        // 2. Grab the Subject Code from Column 0 of the clicked row
        String subjectCode = tblSubjects.getValueAt(selectedRow, 0).toString();
        
        // 3. Double-check with the user (Always safe before deleting!)
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete " + subjectCode + "?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            
            // 4. Send the code to our Controller to delete from memory & text file
            SubjectController controller = new SubjectController();
            controller.deleteSubject(subjectCode);
            
            // 5. Visually remove the row from the table right now
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblSubjects.getModel();
            model.removeRow(selectedRow);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Subject deleted successfully!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void refreshTable(String standardFilter, String searchKeyword) {

    SubjectController controller = new SubjectController();

    java.util.ArrayList<Subject> allSubjects =
            controller.getSubjectList();

    String[] columns = {
        "Subject Code",
        "Subject Name",
        "Standard",
        "Teacher"
    };

    javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel(columns, 0);

    String searchLower = searchKeyword.toLowerCase();

    for (Subject s : allSubjects) {

        boolean matchesStandard =
                standardFilter.equals("All Standards")
                || s.getStandard().equals(standardFilter);

        boolean matchesSearch =
                searchLower.isEmpty()
                || s.getName().toLowerCase().contains(searchLower)
                || s.getCode().toLowerCase().contains(searchLower);

        if (matchesStandard && matchesSearch) {

            String[] rowData = {
                s.getCode(),
                s.getName(),
                s.getStandard(),
                s.getTeacherName()
            };

            model.addRow(rowData);
        }
    }

    tblSubjects.setModel(model);
}
    
    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
       refreshTable(cmbFilter.getSelectedItem().toString(), txtSearch.getText());
    }//GEN-LAST:event_cmbFilterActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // 1. Find out which row they clicked
        int selectedRow = tblSubjects.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a subject in the table to edit.");
            return;
        }

        // 2. Grab the current Code and Name from that row
        String code = tblSubjects.getValueAt(selectedRow, 0).toString();
        String currentName = tblSubjects.getValueAt(selectedRow, 1).toString();

        // 3. Pop-up to ask for the New Name
        String newName = javax.swing.JOptionPane.showInputDialog(this, "Enter a new name for " + code + ":", currentName);
        
        // If they click 'Cancel' or leave it blank, stop the process
        if (newName == null || newName.trim().isEmpty()) { return; } 

        // 4. Pop-up dropdown to ask for the New Standard
        String[] standards = {"Std 4", "Std 5", "Std 6"};
        String newStandard = (String) javax.swing.JOptionPane.showInputDialog(this, "Select the new standard:", "Update Standard", javax.swing.JOptionPane.QUESTION_MESSAGE, null, standards, standards[0]);
        
        if (newStandard == null) { return; }
        // Grab the current teacher name from column 3 (Code is 0, Name is 1, Standard is 2, Teacher is 3)
        String currentTeacher = tblSubjects.getValueAt(selectedRow, 3).toString();

        // Pop-up to ask for the New Teacher
        String newTeacher = javax.swing.JOptionPane.showInputDialog(this, "Enter a new teacher name:", currentTeacher);
        if (newTeacher == null || newTeacher.trim().isEmpty()) { return; } 

        // Send ALL the new data to the Controller! (Make sure you pass all 4 things)
        SubjectController controller = new SubjectController();
        controller.updateSubject(code, newName, newStandard, newTeacher);
        

        // 6. Refresh the table instantly to show the changes
        refreshTable(cmbFilter.getSelectedItem().toString(), txtSearch.getText());
        javax.swing.JOptionPane.showMessageDialog(this, "Subject updated successfully!");
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnOpenMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenMaterialActionPerformed
        // 1. Figure out which subject they clicked
        int selectedRow = tblSubjects.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a subject in the table to manage its materials.");
            return;
        }

        String code = tblSubjects.getValueAt(selectedRow, 0).toString();

        // 2. Create the new pop-up screen
        ManageMaterialsUI manageScreen = new ManageMaterialsUI();
        
        // 3. Send the selected subject code over to the new screen using our custom method!
        manageScreen.setupScreen(code);
        
        // 4. Make it visible
        manageScreen.setVisible(true);
    }//GEN-LAST:event_btnOpenMaterialActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        refreshTable(cmbFilter.getSelectedItem().toString(), txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewRecordsUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnOpenMaterial;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSubjects;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}